stages:
  - build

variables:
  CONTAINER_IMAGE: "ekidd/rust-musl-builder"

build:
  stage: build
  script: |
    docker pull $CONTAINER_IMAGE
    docker run --rm --user "$(id -u)":"$(id -g)" -v "$PWD":/home/rust/src $CONTAINER_IMAGE cargo build --release
  artifacts:
    paths:
      - target/x86_64-unknown-linux-musl/release/sc-audit-event-log-collector
