stages:
  - build

variables:
  CONTAINER_IMAGE: "ekidd/rust-musl-builder"

build:
  stage: build
  script: |
    docker pull $CONTAINER_IMAGE
    docker run --rm -v "$(pwd)":/home/rust/src $CONTAINER_IMAGE ./build.sh
  artifacts:
    expire_in: 1 mo
    paths:
      - target/x86_64-unknown-linux-musl/release/sc-audit-event-log-collector
