stages:
  - build

variables:
  CONTAINER_IMAGE: "rust"

build:
  stage: build
  script: |
    docker pull $CONTAINER_IMAGE
    docker run --rm --user "$(id -u)":"$(id -g)" -v "$PWD":/usr/src/myapp -w /usr/src/myapp $CONTAINER_IMAGE cargo build --release
  artifacts:
    paths:
      - target/release/sc-audit-event-log-collector
